### ISSUE TITLE
Argument to disable face detection

### ISSUE THREAD

**Issue by gaga23** [ChenglongMa/SkinToneClassifier#1]
I had to clone the repository and manually edit the code to disable face dection. I want to run the SkinToneClassifier over images for which the face is already cropped. Running the present code (version 0.1.11) results in either 'NA' (which is what I want) or  some small subregions of the face (which I want to avoid right now).

Some examples:
![2_2_0_1_1_10_2-1](https://user-images.githubusercontent.com/1943792/230134977-9aa9786f-357c-4ab9-acf4-4458623d3a3f.jpg)
![2_2_0_1_1_12_2-1](https://user-images.githubusercontent.com/1943792/230134982-b0c32388-2f9f-45c8-937e-8fc09a7deb70.jpg)

**Comment by ChenglongMa** [comment]
Hi @gaga23, thanks for your comments!

To solve your problem, you can either set `--new_width` to a smaller value, e.g., `--new_width 200` or set `--min_size` to a large value, e.g., `--min_size 500 500`.

I've tested on your first example by running
```bash
stone -i ./example.jpg -d --new_width 200
```
And I got the following result message:

```text
----- Processing example -----
Found 0 face, will detect global skin area instead
Dominant color(s) with proportion: ['#553331', '0.84', '#7B645D', '0.16']
Classified color category: #513b2e, distance: 9.459270010669316
100%|██████████| 1/1 [00:00<00:00,  3.96it/s]
```

Imagine we are using a scanner to scan the image to find a part of the face.
False detections are either because **the image size is too large** or **the scanner is too small** and therefore thinks a small area is a "face".

So the solution as shown above is to adjust the parameter to resize the image or scanner.

Hope it can help!
Thanks!

**Comment by gaga23** [comment]
Thx!
