### ISSUE TITLE
AttributeError: module 'stone' has no attribute 'process'

### ISSUE THREAD

**Issue by ergo70** [ChenglongMa/SkinToneClassifier#15]
The command line Version works, but:

I followed the instructions for using the library.

pip install skin-tone-classifier --upgrade

import stone

result = stone.process('xxx.jpg', image_type='color')

But then:

AttributeError: module 'stone' has no attribute 'process'

Python 3.10.11

**Comment by ChenglongMa** [comment]
Hi @ergo70,

Thanks for your feedback. 

I tried on my side and in a Google Colab session, but it works well.

Can you give me more details to reproduce this problem?
You can also check the Colab example here: [Google Colab](https://colab.research.google.com/drive/1k-cryEZ9PInJRXWIi17ib66ufYV2Ikwe?usp=sharing). It is a running example, so that you can see more intuitively how to use this library.

Thanks!

**Comment by ergo70** [comment]
I tried with your minimal example:

pip uninstall skin-tone-classifier
pip install skin-tone-classifier

import stone

image_path = "https://raw.githubusercontent.com/ChenglongMa/SkinToneClassifier/main/docs/demo.png" # Use the demo.png stored in my repo

result = stone.process(image_path, image_type="color", return_report_image=False)

Traceback (most recent call last):
  File "c:\Devel\SkinToneAPI\stonetest.py", line 5, in <module>
    result = stone.process(image_path, image_type="color", return_report_image=True)
AttributeError: module 'stone' has no attribute 'process'

Maybe because I try it onw Windows 11?

**Comment by ergo70** [comment]
I now tried it on WSL2 Ubuntu 22.04.3 LTS / Python 3.10.12 and it works without problems.

As said, the stone.exe Script also works on Windows. The error occurs only when I try the library in code.

**Comment by ChenglongMa** [comment]
Hi @ergo70,

I'm glad your problem was solved.

Have a nice day :)
